version: "3"

services:

  fizzbuzz:
    build:
      dockerfile: ./Dockerfile-production
      context: ./
    image: fizzbuzz:latest
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    logging:
      options:
        max-size: 200k
  
  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    restart: unless-stopped
    volumes:
      - ./:/etc/prometheus/
      - ./:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - fizzbuzz:fizzbuzz
  
  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - 3000:3000
    links:
      - prometheus:prometheus
    volumes:
      - ./:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  default:
